// src/invoice_generator.js
// Renders a professional USDC invoice as a PNG using sharp (SVG pipeline)
// All user text is XML-escaped before embedding to prevent SVG injection.

const sharp = require("sharp");
const path  = require("path");
const fs    = require("fs");
const os    = require("os");

function escape(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildSvg({ invoiceNumber, clientName, clientEmail, items, dueDate, notes, businessName, walletAddress, issueDate }) {
  const total = items.reduce((s, i) => s + Number(i.quantity || 1) * Number(i.unitPrice || 0), 0);
  const itemRows = items.map(item => {
    const qty      = Number(item.quantity || 1);
    const price    = Number(item.unitPrice || 0);
    const lineTotal = qty * price;
    return `
      <text x="40" y="{Y}" font-size="13" fill="#334155">${escape(item.description)}</text>
      <text x="440" y="{Y}" font-size="13" fill="#334155" text-anchor="middle">${qty}</text>
      <text x="520" y="{Y}" font-size="13" fill="#334155" text-anchor="end">${price.toFixed(2)}</text>
      <text x="620" y="{Y}" font-size="13" fill="#0f766e" text-anchor="end" font-weight="600">${lineTotal.toFixed(2)}</text>
    `;
  });

  let y = 290;
  const rowSpacing = 30;
  const itemsSvg = itemRows.map((row) => {
    const rendered = row.replace(/{Y}/g, String(y));
    y += rowSpacing;
    return rendered;
  }).join("");

  const totalY   = y + 20;
  const notesY   = totalY + 60;
  const walletY  = notesY + (notes ? 50 : 20);
  const footerY  = walletY + 50;
  const svgHeight = footerY + 60;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="680" height="${svgHeight}" viewBox="0 0 680 ${svgHeight}" xmlns="http://www.w3.org/2000/svg" font-family="Arial, Helvetica, sans-serif">
  <!-- Background -->
  <rect width="680" height="${svgHeight}" fill="#f8fafc" rx="12"/>
  <!-- Header stripe -->
  <rect width="680" height="80" fill="#0f766e" rx="12"/>
  <rect y="60" width="680" height="30" fill="#0f766e"/>
  <!-- Header text -->
  <text x="40" y="38" font-size="22" font-weight="700" fill="#ffffff">INVOICE</text>
  <text x="640" y="30" font-size="13" fill="#a7f3d0" text-anchor="end">${escape(businessName)}</text>
  <text x="640" y="48" font-size="12" fill="#6ee7b7" text-anchor="end">#${escape(invoiceNumber)}</text>
  <!-- Meta row -->
  <rect y="80" width="680" height="64" fill="#f0fdf4"/>
  <text x="40"  y="110" font-size="12" fill="#475569">Bill to:</text>
  <text x="40"  y="130" font-size="14" font-weight="600" fill="#1e293b">${escape(clientName)}${clientEmail ? `  ·  ${escape(clientEmail)}` : ""}</text>
  <text x="500" y="110" font-size="12" fill="#475569" text-anchor="end">Issue date:</text>
  <text x="640" y="110" font-size="12" fill="#1e293b" text-anchor="end">${escape(issueDate)}</text>
  <text x="500" y="130" font-size="12" fill="#475569" text-anchor="end">Due date:</text>
  <text x="640" y="130" font-size="12" fill="${dueDate ? "#dc2626" : "#94a3b8"}" text-anchor="end">${escape(dueDate || "On receipt")}</text>
  <!-- Table header -->
  <rect y="148" width="680" height="28" fill="#0f766e" opacity="0.08"/>
  <text x="40"  y="166" font-size="12" font-weight="700" fill="#0f766e">Description</text>
  <text x="440" y="166" font-size="12" font-weight="700" fill="#0f766e" text-anchor="middle">Qty</text>
  <text x="520" y="166" font-size="12" font-weight="700" fill="#0f766e" text-anchor="end">Unit (USDC)</text>
  <text x="620" y="166" font-size="12" font-weight="700" fill="#0f766e" text-anchor="end">Amount</text>
  <!-- Divider -->
  <line x1="30" y1="180" x2="650" y2="180" stroke="#e2e8f0" stroke-width="1"/>
  <!-- Items -->
  ${itemsSvg}
  <!-- Total -->
  <line x1="30" y1="${totalY - 14}" x2="650" y2="${totalY - 14}" stroke="#e2e8f0" stroke-width="1"/>
  <rect x="440" y="${totalY - 4}" width="220" height="36" fill="#0f766e" rx="6"/>
  <text x="460" y="${totalY + 18}" font-size="13" fill="#ffffff" font-weight="700">TOTAL DUE</text>
  <text x="650" y="${totalY + 18}" font-size="16" fill="#ffffff" font-weight="700" text-anchor="end">${total.toFixed(2)} USDC</text>
  ${notes ? `
  <!-- Notes -->
  <text x="40" y="${notesY}" font-size="12" fill="#64748b">Notes: ${escape(notes)}</text>` : ""}
  <!-- Payment address -->
  <rect x="30" y="${walletY - 16}" width="620" height="36" fill="#f0fdf4" rx="6" stroke="#6ee7b7" stroke-width="1"/>
  <text x="40" y="${walletY + 2}" font-size="10" fill="#64748b">Pay to (Arc Testnet USDC):</text>
  <text x="40" y="${walletY + 17}" font-size="10.5" fill="#0f766e" font-weight="600">${escape(walletAddress)}</text>
  <!-- Footer -->
  <text x="340" y="${footerY + 20}" font-size="11" fill="#94a3b8" text-anchor="middle">Generated by PayIT · payit.arc.testnet · Powered by Circle Arc</text>
</svg>`;
}

async function generateInvoicePNG(data) {
  const svg     = buildSvg(data);
  const tmpDir  = os.tmpdir();
  const outPath = path.join(tmpDir, `invoice-${data.invoiceNumber}-${Date.now()}.png`);
  await sharp(Buffer.from(svg)).png().toFile(outPath);
  return outPath;
}

module.exports = { generateInvoicePNG };
